# backend:
#   name: test-repo
backend:
  name: github
  repo: minicreative/april-goldberg
  branch: main
  base_url: https://github-auth.tomasroy.com/
  media_folder: "uploads"
  public_folder: "/uploads"
default_fields: 
  layout_field: &layout_field
    label: Layout
    name: layout
    widget: hidden
    default: page
  title_field: &title_field
    label: Title
    name: title
    widget: string
  position_field: &position_field
    label: Position
    name: position
    widget: number
  permalink_field: &permalink_field
    label: URL
    name: permalink
    widget: string
  content_field: &content_field
    label: Content / Description
    name: body
    widget: richtext
editor:
  preview: false
media_folder: "_uploads"
public_folder: "uploads"
collections:
  - name: "page"
    label: "Pages"
    create: false
    sortable_fields: ['title', 'position']
    files: 
      - file: "index.md"
        label: "Home"
        name: "home"
        fields:
          - *layout_field
          - *title_field
          - *position_field
          - *permalink_field
          - {label: Heading, name: heading, widget: string}
      - file: "about.md"
        label: "About"
        name: "about"
        fields:
          - *layout_field
          - *title_field
          - *position_field
          - *permalink_field
          - *content_field
          - label: Social Media
            name: socialLinks
            widget: list
            collapsed: false
            fields:
              - { label: URL, name: url, widget: string }
              - { label: Font Awesome Icon, name: icon, widget: string }
      - file: "work.md"
        label: "Work"
        name: "work"
        fields:
          - *layout_field
          - *title_field
          - *position_field
          - *permalink_field
  - name: "project"
    label: "Project"
    create: true
    sortable_fields: ['title']
    folder: "_projects"
    fields:
      - *layout_field
      - *title_field
      - *permalink_field
      - *position_field
      - { label: Director, name: director, widget: string }
      - label: Project Type
        name: type
        widget: string
      - *content_field
      - label: Links
        name: links
        widget: list
        collapsed: false
        fields:
          - { label: Title, name: title, widget: string }
          - { label: URL, name: url, widget: string }
      - label: Images
        name: images
        widget: list
        collapsed: false
        field: { label: Image, name: url, widget: image }
        allow_add: true
        allow_remove: true
        allow_reorder: true



          
    
