backend:
  name: test-repo
# backend:
#   name: github
#   repo: minicreative/april-goldberg
#   branch: main
#   base_url: https://github-auth.tomasroy.com/
default_fields: 
  layout_field: &layout_field
    label: Layout
    name: layout
    widget: hidden
    default: page
  title_field: &title_field
    label: Title
    name: title
    widget: string
  position_field: &position_field
    label: Position
    name: position
    widget: number
  permalink_field: &permalink_field
    label: URL
    name: permalink
    widget: string
editor:
  preview: false
media_folder: "_uploads"
public_folder: "uploads"
collections:
  - name: "page"
    label: "Pages"
    create: false
    sortable_fields: ['title', 'position']
    files: 
      - file: "index.md"
        label: "Home"
        name: "home"
        fields:
          - *layout_field
          - *title_field
          - *position_field
          - *permalink_field
          - {label: Heading, name: heading, widget: string}
      - file: "about.md"
        label: "About"
        name: "about"
        fields:
          - *layout_field
          - *title_field
          - *position_field
          - *permalink_field
          - label: Page Content
            name: Content
            widget: markdown
          - label: Social Media
            name: socialLinks
            widget: object
            fields:
              - { label: URL, name: url, widget: string }
              - { label: Font Awesome Icon, name: icon, widget: string }
      - file: "work.md"
        label: "Work"
        name: "work"
        fields:
          - *layout_field
          - *title_field
          - *position_field
          - *permalink_field
  - name: "project"
    label: "Projects"
    create: true
    sortable_fields: ['title']
    folder: "projects"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Director, name: director, widget: string }
      - label: Type
        name: type
        widget: relation
        collection: types
        value_field: title
        search_fields: [title]
      - label: Links
        name: links
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: URL, name: url, widget: string }
      - label: Images
        name: images
        widget: list
        field: { label: Image, name: url, widget: image }
        allow_add: true
        allow_remove: true
        allow_reorder: true
  - name: "type"
    label: "Types"
    create: true
    sortable_fields: ['title']
    folder: "types"
    fields:
      - { label: Title, name: title, widget: string }



          
    
